/* tslint:disable: max-line-length */
// Function creates Genreal Midi Instrument data found in JSON
// const GMInstruments = (function(arr) {
//   var clean = function(name) {
//       return name.replace(/[^a-z0-9 ]/gi, '').replace(/[ ]/g, '_').toLowerCase();
//   };
//   var res = {
//       byName: { },
//       byId: { },
//       byCategory: { }
//   };
//   for (var key in arr) {
//       var list = arr[key];
//       for (var n = 0, length = list.length; n < length; n++) {
//           var instrument = list[n];
//           if (!instrument) continue;
//           var num = parseInt(instrument.substr(0, instrument.indexOf(' ')), 10);
//           instrument = instrument.replace(num + ' ', '');
//           res.byId[--num] =
//           res.byName[clean(instrument)] =
//           {
//               id: clean(instrument),
//               instrument: instrument,
//               number: num,
//               category: key
//           };
//           if (!res.byCategory[clean(key)])
//               res.byCategory[clean(key)] = {};
//           res.byCategory[clean(key)][res.byId[num].id]= res.byId[num];
//       }
//   }
//   return res;
// })({
//   'Piano': ['1 Acoustic Grand Piano', '2 Bright Acoustic Piano', '3 Electric Grand Piano', '4 Honky-tonk Piano', '5 Electric Piano 1', '6 Electric Piano 2', '7 Harpsichord', '8 Clavinet'],
//   'Chromatic Percussion': ['9 Celesta', '10 Glockenspiel', '11 Music Box', '12 Vibraphone', '13 Marimba', '14 Xylophone', '15 Tubular Bells', '16 Dulcimer'],
//   'Organ': ['17 Drawbar Organ', '18 Percussive Organ', '19 Rock Organ', '20 Church Organ', '21 Reed Organ', '22 Accordion', '23 Harmonica', '24 Tango Accordion'],
//   'Guitar': ['25 Acoustic Guitar (nylon)', '26 Acoustic Guitar (steel)', '27 Electric Guitar (jazz)', '28 Electric Guitar (clean)', '29 Electric Guitar (muted)', '30 Overdriven Guitar', '31 Distortion Guitar', '32 Guitar Harmonics'],
//   'Bass': ['33 Acoustic Bass', '34 Electric Bass (finger)', '35 Electric Bass (pick)', '36 Fretless Bass', '37 Slap Bass 1', '38 Slap Bass 2', '39 Synth Bass 1', '40 Synth Bass 2'],
//   'Strings': ['41 Violin', '42 Viola', '43 Cello', '44 Contrabass', '45 Tremolo Strings', '46 Pizzicato Strings', '47 Orchestral Harp', '48 Timpani'],
//   'Ensemble': ['49 String Ensemble 1', '50 String Ensemble 2', '51 Synth Strings 1', '52 Synth Strings 2', '53 Choir Aahs', '54 Voice Oohs', '55 Synth Choir', '56 Orchestra Hit'],
//   'Brass': ['57 Trumpet', '58 Trombone', '59 Tuba', '60 Muted Trumpet', '61 French Horn', '62 Brass Section', '63 Synth Brass 1', '64 Synth Brass 2'],
//   'Reed': ['65 Soprano Sax', '66 Alto Sax', '67 Tenor Sax', '68 Baritone Sax', '69 Oboe', '70 English Horn', '71 Bassoon', '72 Clarinet'],
//   'Pipe': ['73 Piccolo', '74 Flute', '75 Recorder', '76 Pan Flute', '77 Blown Bottle', '78 Shakuhachi', '79 Whistle', '80 Ocarina'],
//   'Synth Lead': ['81 Lead 1 (square)', '82 Lead 2 (sawtooth)', '83 Lead 3 (calliope)', '84 Lead 4 (chiff)', '85 Lead 5 (charang)', '86 Lead 6 (voice)', '87 Lead 7 (fifths)', '88 Lead 8 (bass + lead)'],
//   'Synth Pad': ['89 Pad 1 (new age)', '90 Pad 2 (warm)', '91 Pad 3 (polysynth)', '92 Pad 4 (choir)', '93 Pad 5 (bowed)', '94 Pad 6 (metallic)', '95 Pad 7 (halo)', '96 Pad 8 (sweep)'],
//   'Synth Effects': ['97 FX 1 (rain)', '98 FX 2 (soundtrack)', '99 FX 3 (crystal)', '100 FX 4 (atmosphere)', '101 FX 5 (brightness)', '102 FX 6 (goblins)', '103 FX 7 (echoes)', '104 FX 8 (sci-fi)'],
//   'Ethnic': ['105 Sitar', '106 Banjo', '107 Shamisen', '108 Koto', '109 Kalimba', '110 Bagpipe', '111 Fiddle', '112 Shanai'],
//   'Percussive': ['113 Tinkle Bell', '114 Agogo', '115 Steel Drums', '116 Woodblock', '117 Taiko Drum', '118 Melodic Tom', '119 Synth Drum'],
//   'Sound effects': ['120 Reverse Cymbal', '121 Guitar Fret Noise', '122 Breath Noise', '123 Seashore', '124 Bird Tweet', '125 Telephone Ring', '126 Helicopter', '127 Applause', '128 Gunshot']
// });

export const GMInstruments = Object.freeze({
  byName: {
    acoustic_grand_piano: {
      id: "acoustic_grand_piano",
      instrument: "Acoustic Grand Piano",
      number: 0,
      category: "Piano",
    },
    bright_acoustic_piano: {
      id: "bright_acoustic_piano",
      instrument: "Bright Acoustic Piano",
      number: 1,
      category: "Piano",
    },
    electric_grand_piano: {
      id: "electric_grand_piano",
      instrument: "Electric Grand Piano",
      number: 2,
      category: "Piano",
    },
    honkytonk_piano: {
      id: "honkytonk_piano",
      instrument: "Honky-tonk Piano",
      number: 3,
      category: "Piano",
    },
    electric_piano_1: {
      id: "electric_piano_1",
      instrument: "Electric Piano 1",
      number: 4,
      category: "Piano",
    },
    electric_piano_2: {
      id: "electric_piano_2",
      instrument: "Electric Piano 2",
      number: 5,
      category: "Piano",
    },
    harpsichord: {
      id: "harpsichord",
      instrument: "Harpsichord",
      number: 6,
      category: "Piano",
    },
    clavinet: {
      id: "clavinet",
      instrument: "Clavinet",
      number: 7,
      category: "Piano",
    },
    celesta: {
      id: "celesta",
      instrument: "Celesta",
      number: 8,
      category: "Chromatic Percussion",
    },
    glockenspiel: {
      id: "glockenspiel",
      instrument: "Glockenspiel",
      number: 9,
      category: "Chromatic Percussion",
    },
    music_box: {
      id: "music_box",
      instrument: "Music Box",
      number: 10,
      category: "Chromatic Percussion",
    },
    vibraphone: {
      id: "vibraphone",
      instrument: "Vibraphone",
      number: 11,
      category: "Chromatic Percussion",
    },
    marimba: {
      id: "marimba",
      instrument: "Marimba",
      number: 12,
      category: "Chromatic Percussion",
    },
    xylophone: {
      id: "xylophone",
      instrument: "Xylophone",
      number: 13,
      category: "Chromatic Percussion",
    },
    tubular_bells: {
      id: "tubular_bells",
      instrument: "Tubular Bells",
      number: 14,
      category: "Chromatic Percussion",
    },
    dulcimer: {
      id: "dulcimer",
      instrument: "Dulcimer",
      number: 15,
      category: "Chromatic Percussion",
    },
    drawbar_organ: {
      id: "drawbar_organ",
      instrument: "Drawbar Organ",
      number: 16,
      category: "Organ",
    },
    percussive_organ: {
      id: "percussive_organ",
      instrument: "Percussive Organ",
      number: 17,
      category: "Organ",
    },
    rock_organ: {
      id: "rock_organ",
      instrument: "Rock Organ",
      number: 18,
      category: "Organ",
    },
    church_organ: {
      id: "church_organ",
      instrument: "Church Organ",
      number: 19,
      category: "Organ",
    },
    reed_organ: {
      id: "reed_organ",
      instrument: "Reed Organ",
      number: 20,
      category: "Organ",
    },
    accordion: {
      id: "accordion",
      instrument: "Accordion",
      number: 21,
      category: "Organ",
    },
    harmonica: {
      id: "harmonica",
      instrument: "Harmonica",
      number: 22,
      category: "Organ",
    },
    tango_accordion: {
      id: "tango_accordion",
      instrument: "Tango Accordion",
      number: 23,
      category: "Organ",
    },
    acoustic_guitar_nylon: {
      id: "acoustic_guitar_nylon",
      instrument: "Acoustic Guitar (nylon)",
      number: 24,
      category: "Guitar",
    },
    acoustic_guitar_steel: {
      id: "acoustic_guitar_steel",
      instrument: "Acoustic Guitar (steel)",
      number: 25,
      category: "Guitar",
    },
    electric_guitar_jazz: {
      id: "electric_guitar_jazz",
      instrument: "Electric Guitar (jazz)",
      number: 26,
      category: "Guitar",
    },
    electric_guitar_clean: {
      id: "electric_guitar_clean",
      instrument: "Electric Guitar (clean)",
      number: 27,
      category: "Guitar",
    },
    electric_guitar_muted: {
      id: "electric_guitar_muted",
      instrument: "Electric Guitar (muted)",
      number: 28,
      category: "Guitar",
    },
    overdriven_guitar: {
      id: "overdriven_guitar",
      instrument: "Overdriven Guitar",
      number: 29,
      category: "Guitar",
    },
    distortion_guitar: {
      id: "distortion_guitar",
      instrument: "Distortion Guitar",
      number: 30,
      category: "Guitar",
    },
    guitar_harmonics: {
      id: "guitar_harmonics",
      instrument: "Guitar Harmonics",
      number: 31,
      category: "Guitar",
    },
    acoustic_bass: {
      id: "acoustic_bass",
      instrument: "Acoustic Bass",
      number: 32,
      category: "Bass",
    },
    electric_bass_finger: {
      id: "electric_bass_finger",
      instrument: "Electric Bass (finger)",
      number: 33,
      category: "Bass",
    },
    electric_bass_pick: {
      id: "electric_bass_pick",
      instrument: "Electric Bass (pick)",
      number: 34,
      category: "Bass",
    },
    fretless_bass: {
      id: "fretless_bass",
      instrument: "Fretless Bass",
      number: 35,
      category: "Bass",
    },
    slap_bass_1: {
      id: "slap_bass_1",
      instrument: "Slap Bass 1",
      number: 36,
      category: "Bass",
    },
    slap_bass_2: {
      id: "slap_bass_2",
      instrument: "Slap Bass 2",
      number: 37,
      category: "Bass",
    },
    synth_bass_1: {
      id: "synth_bass_1",
      instrument: "Synth Bass 1",
      number: 38,
      category: "Bass",
    },
    synth_bass_2: {
      id: "synth_bass_2",
      instrument: "Synth Bass 2",
      number: 39,
      category: "Bass",
    },
    violin: {
      id: "violin",
      instrument: "Violin",
      number: 40,
      category: "Strings",
    },
    viola: {
      id: "viola",
      instrument: "Viola",
      number: 41,
      category: "Strings",
    },
    cello: {
      id: "cello",
      instrument: "Cello",
      number: 42,
      category: "Strings",
    },
    contrabass: {
      id: "contrabass",
      instrument: "Contrabass",
      number: 43,
      category: "Strings",
    },
    tremolo_strings: {
      id: "tremolo_strings",
      instrument: "Tremolo Strings",
      number: 44,
      category: "Strings",
    },
    pizzicato_strings: {
      id: "pizzicato_strings",
      instrument: "Pizzicato Strings",
      number: 45,
      category: "Strings",
    },
    orchestral_harp: {
      id: "orchestral_harp",
      instrument: "Orchestral Harp",
      number: 46,
      category: "Strings",
    },
    timpani: {
      id: "timpani",
      instrument: "Timpani",
      number: 47,
      category: "Strings",
    },
    string_ensemble_1: {
      id: "string_ensemble_1",
      instrument: "String Ensemble 1",
      number: 48,
      category: "Ensemble",
    },
    string_ensemble_2: {
      id: "string_ensemble_2",
      instrument: "String Ensemble 2",
      number: 49,
      category: "Ensemble",
    },
    synth_strings_1: {
      id: "synth_strings_1",
      instrument: "Synth Strings 1",
      number: 50,
      category: "Ensemble",
    },
    synth_strings_2: {
      id: "synth_strings_2",
      instrument: "Synth Strings 2",
      number: 51,
      category: "Ensemble",
    },
    choir_aahs: {
      id: "choir_aahs",
      instrument: "Choir Aahs",
      number: 52,
      category: "Ensemble",
    },
    voice_oohs: {
      id: "voice_oohs",
      instrument: "Voice Oohs",
      number: 53,
      category: "Ensemble",
    },
    synth_choir: {
      id: "synth_choir",
      instrument: "Synth Choir",
      number: 54,
      category: "Ensemble",
    },
    orchestra_hit: {
      id: "orchestra_hit",
      instrument: "Orchestra Hit",
      number: 55,
      category: "Ensemble",
    },
    trumpet: {
      id: "trumpet",
      instrument: "Trumpet",
      number: 56,
      category: "Brass",
    },
    trombone: {
      id: "trombone",
      instrument: "Trombone",
      number: 57,
      category: "Brass",
    },
    tuba: {
      id: "tuba",
      instrument: "Tuba",
      number: 58,
      category: "Brass",
    },
    muted_trumpet: {
      id: "muted_trumpet",
      instrument: "Muted Trumpet",
      number: 59,
      category: "Brass",
    },
    french_horn: {
      id: "french_horn",
      instrument: "French Horn",
      number: 60,
      category: "Brass",
    },
    brass_section: {
      id: "brass_section",
      instrument: "Brass Section",
      number: 61,
      category: "Brass",
    },
    synth_brass_1: {
      id: "synth_brass_1",
      instrument: "Synth Brass 1",
      number: 62,
      category: "Brass",
    },
    synth_brass_2: {
      id: "synth_brass_2",
      instrument: "Synth Brass 2",
      number: 63,
      category: "Brass",
    },
    soprano_sax: {
      id: "soprano_sax",
      instrument: "Soprano Sax",
      number: 64,
      category: "Reed",
    },
    alto_sax: {
      id: "alto_sax",
      instrument: "Alto Sax",
      number: 65,
      category: "Reed",
    },
    tenor_sax: {
      id: "tenor_sax",
      instrument: "Tenor Sax",
      number: 66,
      category: "Reed",
    },
    baritone_sax: {
      id: "baritone_sax",
      instrument: "Baritone Sax",
      number: 67,
      category: "Reed",
    },
    oboe: {
      id: "oboe",
      instrument: "Oboe",
      number: 68,
      category: "Reed",
    },
    english_horn: {
      id: "english_horn",
      instrument: "English Horn",
      number: 69,
      category: "Reed",
    },
    bassoon: {
      id: "bassoon",
      instrument: "Bassoon",
      number: 70,
      category: "Reed",
    },
    clarinet: {
      id: "clarinet",
      instrument: "Clarinet",
      number: 71,
      category: "Reed",
    },
    piccolo: {
      id: "piccolo",
      instrument: "Piccolo",
      number: 72,
      category: "Pipe",
    },
    flute: {
      id: "flute",
      instrument: "Flute",
      number: 73,
      category: "Pipe",
    },
    recorder: {
      id: "recorder",
      instrument: "Recorder",
      number: 74,
      category: "Pipe",
    },
    pan_flute: {
      id: "pan_flute",
      instrument: "Pan Flute",
      number: 75,
      category: "Pipe",
    },
    blown_bottle: {
      id: "blown_bottle",
      instrument: "Blown Bottle",
      number: 76,
      category: "Pipe",
    },
    shakuhachi: {
      id: "shakuhachi",
      instrument: "Shakuhachi",
      number: 77,
      category: "Pipe",
    },
    whistle: {
      id: "whistle",
      instrument: "Whistle",
      number: 78,
      category: "Pipe",
    },
    ocarina: {
      id: "ocarina",
      instrument: "Ocarina",
      number: 79,
      category: "Pipe",
    },
    lead_1_square: {
      id: "lead_1_square",
      instrument: "Lead 1 (square)",
      number: 80,
      category: "Synth Lead",
    },
    lead_2_sawtooth: {
      id: "lead_2_sawtooth",
      instrument: "Lead 2 (sawtooth)",
      number: 81,
      category: "Synth Lead",
    },
    lead_3_calliope: {
      id: "lead_3_calliope",
      instrument: "Lead 3 (calliope)",
      number: 82,
      category: "Synth Lead",
    },
    lead_4_chiff: {
      id: "lead_4_chiff",
      instrument: "Lead 4 (chiff)",
      number: 83,
      category: "Synth Lead",
    },
    lead_5_charang: {
      id: "lead_5_charang",
      instrument: "Lead 5 (charang)",
      number: 84,
      category: "Synth Lead",
    },
    lead_6_voice: {
      id: "lead_6_voice",
      instrument: "Lead 6 (voice)",
      number: 85,
      category: "Synth Lead",
    },
    lead_7_fifths: {
      id: "lead_7_fifths",
      instrument: "Lead 7 (fifths)",
      number: 86,
      category: "Synth Lead",
    },
    lead_8_bass__lead: {
      id: "lead_8_bass__lead",
      instrument: "Lead 8 (bass + lead)",
      number: 87,
      category: "Synth Lead",
    },
    pad_1_new_age: {
      id: "pad_1_new_age",
      instrument: "Pad 1 (new age)",
      number: 88,
      category: "Synth Pad",
    },
    pad_2_warm: {
      id: "pad_2_warm",
      instrument: "Pad 2 (warm)",
      number: 89,
      category: "Synth Pad",
    },
    pad_3_polysynth: {
      id: "pad_3_polysynth",
      instrument: "Pad 3 (polysynth)",
      number: 90,
      category: "Synth Pad",
    },
    pad_4_choir: {
      id: "pad_4_choir",
      instrument: "Pad 4 (choir)",
      number: 91,
      category: "Synth Pad",
    },
    pad_5_bowed: {
      id: "pad_5_bowed",
      instrument: "Pad 5 (bowed)",
      number: 92,
      category: "Synth Pad",
    },
    pad_6_metallic: {
      id: "pad_6_metallic",
      instrument: "Pad 6 (metallic)",
      number: 93,
      category: "Synth Pad",
    },
    pad_7_halo: {
      id: "pad_7_halo",
      instrument: "Pad 7 (halo)",
      number: 94,
      category: "Synth Pad",
    },
    pad_8_sweep: {
      id: "pad_8_sweep",
      instrument: "Pad 8 (sweep)",
      number: 95,
      category: "Synth Pad",
    },
    fx_1_rain: {
      id: "fx_1_rain",
      instrument: "FX 1 (rain)",
      number: 96,
      category: "Synth Effects",
    },
    fx_2_soundtrack: {
      id: "fx_2_soundtrack",
      instrument: "FX 2 (soundtrack)",
      number: 97,
      category: "Synth Effects",
    },
    fx_3_crystal: {
      id: "fx_3_crystal",
      instrument: "FX 3 (crystal)",
      number: 98,
      category: "Synth Effects",
    },
    fx_4_atmosphere: {
      id: "fx_4_atmosphere",
      instrument: "FX 4 (atmosphere)",
      number: 99,
      category: "Synth Effects",
    },
    fx_5_brightness: {
      id: "fx_5_brightness",
      instrument: "FX 5 (brightness)",
      number: 100,
      category: "Synth Effects",
    },
    fx_6_goblins: {
      id: "fx_6_goblins",
      instrument: "FX 6 (goblins)",
      number: 101,
      category: "Synth Effects",
    },
    fx_7_echoes: {
      id: "fx_7_echoes",
      instrument: "FX 7 (echoes)",
      number: 102,
      category: "Synth Effects",
    },
    fx_8_scifi: {
      id: "fx_8_scifi",
      instrument: "FX 8 (sci-fi)",
      number: 103,
      category: "Synth Effects",
    },
    sitar: {
      id: "sitar",
      instrument: "Sitar",
      number: 104,
      category: "Ethnic",
    },
    banjo: {
      id: "banjo",
      instrument: "Banjo",
      number: 105,
      category: "Ethnic",
    },
    shamisen: {
      id: "shamisen",
      instrument: "Shamisen",
      number: 106,
      category: "Ethnic",
    },
    koto: {
      id: "koto",
      instrument: "Koto",
      number: 107,
      category: "Ethnic",
    },
    kalimba: {
      id: "kalimba",
      instrument: "Kalimba",
      number: 108,
      category: "Ethnic",
    },
    bagpipe: {
      id: "bagpipe",
      instrument: "Bagpipe",
      number: 109,
      category: "Ethnic",
    },
    fiddle: {
      id: "fiddle",
      instrument: "Fiddle",
      number: 110,
      category: "Ethnic",
    },
    shanai: {
      id: "shanai",
      instrument: "Shanai",
      number: 111,
      category: "Ethnic",
    },
    tinkle_bell: {
      id: "tinkle_bell",
      instrument: "Tinkle Bell",
      number: 112,
      category: "Percussive",
    },
    agogo: {
      id: "agogo",
      instrument: "Agogo",
      number: 113,
      category: "Percussive",
    },
    steel_drums: {
      id: "steel_drums",
      instrument: "Steel Drums",
      number: 114,
      category: "Percussive",
    },
    woodblock: {
      id: "woodblock",
      instrument: "Woodblock",
      number: 115,
      category: "Percussive",
    },
    taiko_drum: {
      id: "taiko_drum",
      instrument: "Taiko Drum",
      number: 116,
      category: "Percussive",
    },
    melodic_tom: {
      id: "melodic_tom",
      instrument: "Melodic Tom",
      number: 117,
      category: "Percussive",
    },
    synth_drum: {
      id: "synth_drum",
      instrument: "Synth Drum",
      number: 118,
      category: "Percussive",
    },
    reverse_cymbal: {
      id: "reverse_cymbal",
      instrument: "Reverse Cymbal",
      number: 119,
      category: "Sound effects",
    },
    guitar_fret_noise: {
      id: "guitar_fret_noise",
      instrument: "Guitar Fret Noise",
      number: 120,
      category: "Sound effects",
    },
    breath_noise: {
      id: "breath_noise",
      instrument: "Breath Noise",
      number: 121,
      category: "Sound effects",
    },
    seashore: {
      id: "seashore",
      instrument: "Seashore",
      number: 122,
      category: "Sound effects",
    },
    bird_tweet: {
      id: "bird_tweet",
      instrument: "Bird Tweet",
      number: 123,
      category: "Sound effects",
    },
    telephone_ring: {
      id: "telephone_ring",
      instrument: "Telephone Ring",
      number: 124,
      category: "Sound effects",
    },
    helicopter: {
      id: "helicopter",
      instrument: "Helicopter",
      number: 125,
      category: "Sound effects",
    },
    applause: {
      id: "applause",
      instrument: "Applause",
      number: 126,
      category: "Sound effects",
    },
    gunshot: {
      id: "gunshot",
      instrument: "Gunshot",
      number: 127,
      category: "Sound effects",
    },
  },
  byId: {
    "0": {
      id: "acoustic_grand_piano",
      instrument: "Acoustic Grand Piano",
      number: 0,
      category: "Piano",
    },
    "1": {
      id: "bright_acoustic_piano",
      instrument: "Bright Acoustic Piano",
      number: 1,
      category: "Piano",
    },
    "2": {
      id: "electric_grand_piano",
      instrument: "Electric Grand Piano",
      number: 2,
      category: "Piano",
    },
    "3": {
      id: "honkytonk_piano",
      instrument: "Honky-tonk Piano",
      number: 3,
      category: "Piano",
    },
    "4": {
      id: "electric_piano_1",
      instrument: "Electric Piano 1",
      number: 4,
      category: "Piano",
    },
    "5": {
      id: "electric_piano_2",
      instrument: "Electric Piano 2",
      number: 5,
      category: "Piano",
    },
    "6": {
      id: "harpsichord",
      instrument: "Harpsichord",
      number: 6,
      category: "Piano",
    },
    "7": {
      id: "clavinet",
      instrument: "Clavinet",
      number: 7,
      category: "Piano",
    },
    "8": {
      id: "celesta",
      instrument: "Celesta",
      number: 8,
      category: "Chromatic Percussion",
    },
    "9": {
      id: "glockenspiel",
      instrument: "Glockenspiel",
      number: 9,
      category: "Chromatic Percussion",
    },
    "10": {
      id: "music_box",
      instrument: "Music Box",
      number: 10,
      category: "Chromatic Percussion",
    },
    "11": {
      id: "vibraphone",
      instrument: "Vibraphone",
      number: 11,
      category: "Chromatic Percussion",
    },
    "12": {
      id: "marimba",
      instrument: "Marimba",
      number: 12,
      category: "Chromatic Percussion",
    },
    "13": {
      id: "xylophone",
      instrument: "Xylophone",
      number: 13,
      category: "Chromatic Percussion",
    },
    "14": {
      id: "tubular_bells",
      instrument: "Tubular Bells",
      number: 14,
      category: "Chromatic Percussion",
    },
    "15": {
      id: "dulcimer",
      instrument: "Dulcimer",
      number: 15,
      category: "Chromatic Percussion",
    },
    "16": {
      id: "drawbar_organ",
      instrument: "Drawbar Organ",
      number: 16,
      category: "Organ",
    },
    "17": {
      id: "percussive_organ",
      instrument: "Percussive Organ",
      number: 17,
      category: "Organ",
    },
    "18": {
      id: "rock_organ",
      instrument: "Rock Organ",
      number: 18,
      category: "Organ",
    },
    "19": {
      id: "church_organ",
      instrument: "Church Organ",
      number: 19,
      category: "Organ",
    },
    "20": {
      id: "reed_organ",
      instrument: "Reed Organ",
      number: 20,
      category: "Organ",
    },
    "21": {
      id: "accordion",
      instrument: "Accordion",
      number: 21,
      category: "Organ",
    },
    "22": {
      id: "harmonica",
      instrument: "Harmonica",
      number: 22,
      category: "Organ",
    },
    "23": {
      id: "tango_accordion",
      instrument: "Tango Accordion",
      number: 23,
      category: "Organ",
    },
    "24": {
      id: "acoustic_guitar_nylon",
      instrument: "Acoustic Guitar (nylon)",
      number: 24,
      category: "Guitar",
    },
    "25": {
      id: "acoustic_guitar_steel",
      instrument: "Acoustic Guitar (steel)",
      number: 25,
      category: "Guitar",
    },
    "26": {
      id: "electric_guitar_jazz",
      instrument: "Electric Guitar (jazz)",
      number: 26,
      category: "Guitar",
    },
    "27": {
      id: "electric_guitar_clean",
      instrument: "Electric Guitar (clean)",
      number: 27,
      category: "Guitar",
    },
    "28": {
      id: "electric_guitar_muted",
      instrument: "Electric Guitar (muted)",
      number: 28,
      category: "Guitar",
    },
    "29": {
      id: "overdriven_guitar",
      instrument: "Overdriven Guitar",
      number: 29,
      category: "Guitar",
    },
    "30": {
      id: "distortion_guitar",
      instrument: "Distortion Guitar",
      number: 30,
      category: "Guitar",
    },
    "31": {
      id: "guitar_harmonics",
      instrument: "Guitar Harmonics",
      number: 31,
      category: "Guitar",
    },
    "32": {
      id: "acoustic_bass",
      instrument: "Acoustic Bass",
      number: 32,
      category: "Bass",
    },
    "33": {
      id: "electric_bass_finger",
      instrument: "Electric Bass (finger)",
      number: 33,
      category: "Bass",
    },
    "34": {
      id: "electric_bass_pick",
      instrument: "Electric Bass (pick)",
      number: 34,
      category: "Bass",
    },
    "35": {
      id: "fretless_bass",
      instrument: "Fretless Bass",
      number: 35,
      category: "Bass",
    },
    "36": {
      id: "slap_bass_1",
      instrument: "Slap Bass 1",
      number: 36,
      category: "Bass",
    },
    "37": {
      id: "slap_bass_2",
      instrument: "Slap Bass 2",
      number: 37,
      category: "Bass",
    },
    "38": {
      id: "synth_bass_1",
      instrument: "Synth Bass 1",
      number: 38,
      category: "Bass",
    },
    "39": {
      id: "synth_bass_2",
      instrument: "Synth Bass 2",
      number: 39,
      category: "Bass",
    },
    "40": {
      id: "violin",
      instrument: "Violin",
      number: 40,
      category: "Strings",
    },
    "41": {
      id: "viola",
      instrument: "Viola",
      number: 41,
      category: "Strings",
    },
    "42": {
      id: "cello",
      instrument: "Cello",
      number: 42,
      category: "Strings",
    },
    "43": {
      id: "contrabass",
      instrument: "Contrabass",
      number: 43,
      category: "Strings",
    },
    "44": {
      id: "tremolo_strings",
      instrument: "Tremolo Strings",
      number: 44,
      category: "Strings",
    },
    "45": {
      id: "pizzicato_strings",
      instrument: "Pizzicato Strings",
      number: 45,
      category: "Strings",
    },
    "46": {
      id: "orchestral_harp",
      instrument: "Orchestral Harp",
      number: 46,
      category: "Strings",
    },
    "47": {
      id: "timpani",
      instrument: "Timpani",
      number: 47,
      category: "Strings",
    },
    "48": {
      id: "string_ensemble_1",
      instrument: "String Ensemble 1",
      number: 48,
      category: "Ensemble",
    },
    "49": {
      id: "string_ensemble_2",
      instrument: "String Ensemble 2",
      number: 49,
      category: "Ensemble",
    },
    "50": {
      id: "synth_strings_1",
      instrument: "Synth Strings 1",
      number: 50,
      category: "Ensemble",
    },
    "51": {
      id: "synth_strings_2",
      instrument: "Synth Strings 2",
      number: 51,
      category: "Ensemble",
    },
    "52": {
      id: "choir_aahs",
      instrument: "Choir Aahs",
      number: 52,
      category: "Ensemble",
    },
    "53": {
      id: "voice_oohs",
      instrument: "Voice Oohs",
      number: 53,
      category: "Ensemble",
    },
    "54": {
      id: "synth_choir",
      instrument: "Synth Choir",
      number: 54,
      category: "Ensemble",
    },
    "55": {
      id: "orchestra_hit",
      instrument: "Orchestra Hit",
      number: 55,
      category: "Ensemble",
    },
    "56": {
      id: "trumpet",
      instrument: "Trumpet",
      number: 56,
      category: "Brass",
    },
    "57": {
      id: "trombone",
      instrument: "Trombone",
      number: 57,
      category: "Brass",
    },
    "58": {
      id: "tuba",
      instrument: "Tuba",
      number: 58,
      category: "Brass",
    },
    "59": {
      id: "muted_trumpet",
      instrument: "Muted Trumpet",
      number: 59,
      category: "Brass",
    },
    "60": {
      id: "french_horn",
      instrument: "French Horn",
      number: 60,
      category: "Brass",
    },
    "61": {
      id: "brass_section",
      instrument: "Brass Section",
      number: 61,
      category: "Brass",
    },
    "62": {
      id: "synth_brass_1",
      instrument: "Synth Brass 1",
      number: 62,
      category: "Brass",
    },
    "63": {
      id: "synth_brass_2",
      instrument: "Synth Brass 2",
      number: 63,
      category: "Brass",
    },
    "64": {
      id: "soprano_sax",
      instrument: "Soprano Sax",
      number: 64,
      category: "Reed",
    },
    "65": {
      id: "alto_sax",
      instrument: "Alto Sax",
      number: 65,
      category: "Reed",
    },
    "66": {
      id: "tenor_sax",
      instrument: "Tenor Sax",
      number: 66,
      category: "Reed",
    },
    "67": {
      id: "baritone_sax",
      instrument: "Baritone Sax",
      number: 67,
      category: "Reed",
    },
    "68": {
      id: "oboe",
      instrument: "Oboe",
      number: 68,
      category: "Reed",
    },
    "69": {
      id: "english_horn",
      instrument: "English Horn",
      number: 69,
      category: "Reed",
    },
    "70": {
      id: "bassoon",
      instrument: "Bassoon",
      number: 70,
      category: "Reed",
    },
    "71": {
      id: "clarinet",
      instrument: "Clarinet",
      number: 71,
      category: "Reed",
    },
    "72": {
      id: "piccolo",
      instrument: "Piccolo",
      number: 72,
      category: "Pipe",
    },
    "73": {
      id: "flute",
      instrument: "Flute",
      number: 73,
      category: "Pipe",
    },
    "74": {
      id: "recorder",
      instrument: "Recorder",
      number: 74,
      category: "Pipe",
    },
    "75": {
      id: "pan_flute",
      instrument: "Pan Flute",
      number: 75,
      category: "Pipe",
    },
    "76": {
      id: "blown_bottle",
      instrument: "Blown Bottle",
      number: 76,
      category: "Pipe",
    },
    "77": {
      id: "shakuhachi",
      instrument: "Shakuhachi",
      number: 77,
      category: "Pipe",
    },
    "78": {
      id: "whistle",
      instrument: "Whistle",
      number: 78,
      category: "Pipe",
    },
    "79": {
      id: "ocarina",
      instrument: "Ocarina",
      number: 79,
      category: "Pipe",
    },
    "80": {
      id: "lead_1_square",
      instrument: "Lead 1 (square)",
      number: 80,
      category: "Synth Lead",
    },
    "81": {
      id: "lead_2_sawtooth",
      instrument: "Lead 2 (sawtooth)",
      number: 81,
      category: "Synth Lead",
    },
    "82": {
      id: "lead_3_calliope",
      instrument: "Lead 3 (calliope)",
      number: 82,
      category: "Synth Lead",
    },
    "83": {
      id: "lead_4_chiff",
      instrument: "Lead 4 (chiff)",
      number: 83,
      category: "Synth Lead",
    },
    "84": {
      id: "lead_5_charang",
      instrument: "Lead 5 (charang)",
      number: 84,
      category: "Synth Lead",
    },
    "85": {
      id: "lead_6_voice",
      instrument: "Lead 6 (voice)",
      number: 85,
      category: "Synth Lead",
    },
    "86": {
      id: "lead_7_fifths",
      instrument: "Lead 7 (fifths)",
      number: 86,
      category: "Synth Lead",
    },
    "87": {
      id: "lead_8_bass__lead",
      instrument: "Lead 8 (bass + lead)",
      number: 87,
      category: "Synth Lead",
    },
    "88": {
      id: "pad_1_new_age",
      instrument: "Pad 1 (new age)",
      number: 88,
      category: "Synth Pad",
    },
    "89": {
      id: "pad_2_warm",
      instrument: "Pad 2 (warm)",
      number: 89,
      category: "Synth Pad",
    },
    "90": {
      id: "pad_3_polysynth",
      instrument: "Pad 3 (polysynth)",
      number: 90,
      category: "Synth Pad",
    },
    "91": {
      id: "pad_4_choir",
      instrument: "Pad 4 (choir)",
      number: 91,
      category: "Synth Pad",
    },
    "92": {
      id: "pad_5_bowed",
      instrument: "Pad 5 (bowed)",
      number: 92,
      category: "Synth Pad",
    },
    "93": {
      id: "pad_6_metallic",
      instrument: "Pad 6 (metallic)",
      number: 93,
      category: "Synth Pad",
    },
    "94": {
      id: "pad_7_halo",
      instrument: "Pad 7 (halo)",
      number: 94,
      category: "Synth Pad",
    },
    "95": {
      id: "pad_8_sweep",
      instrument: "Pad 8 (sweep)",
      number: 95,
      category: "Synth Pad",
    },
    "96": {
      id: "fx_1_rain",
      instrument: "FX 1 (rain)",
      number: 96,
      category: "Synth Effects",
    },
    "97": {
      id: "fx_2_soundtrack",
      instrument: "FX 2 (soundtrack)",
      number: 97,
      category: "Synth Effects",
    },
    "98": {
      id: "fx_3_crystal",
      instrument: "FX 3 (crystal)",
      number: 98,
      category: "Synth Effects",
    },
    "99": {
      id: "fx_4_atmosphere",
      instrument: "FX 4 (atmosphere)",
      number: 99,
      category: "Synth Effects",
    },
    "100": {
      id: "fx_5_brightness",
      instrument: "FX 5 (brightness)",
      number: 100,
      category: "Synth Effects",
    },
    "101": {
      id: "fx_6_goblins",
      instrument: "FX 6 (goblins)",
      number: 101,
      category: "Synth Effects",
    },
    "102": {
      id: "fx_7_echoes",
      instrument: "FX 7 (echoes)",
      number: 102,
      category: "Synth Effects",
    },
    "103": {
      id: "fx_8_scifi",
      instrument: "FX 8 (sci-fi)",
      number: 103,
      category: "Synth Effects",
    },
    "104": {
      id: "sitar",
      instrument: "Sitar",
      number: 104,
      category: "Ethnic",
    },
    "105": {
      id: "banjo",
      instrument: "Banjo",
      number: 105,
      category: "Ethnic",
    },
    "106": {
      id: "shamisen",
      instrument: "Shamisen",
      number: 106,
      category: "Ethnic",
    },
    "107": {
      id: "koto",
      instrument: "Koto",
      number: 107,
      category: "Ethnic",
    },
    "108": {
      id: "kalimba",
      instrument: "Kalimba",
      number: 108,
      category: "Ethnic",
    },
    "109": {
      id: "bagpipe",
      instrument: "Bagpipe",
      number: 109,
      category: "Ethnic",
    },
    "110": {
      id: "fiddle",
      instrument: "Fiddle",
      number: 110,
      category: "Ethnic",
    },
    "111": {
      id: "shanai",
      instrument: "Shanai",
      number: 111,
      category: "Ethnic",
    },
    "112": {
      id: "tinkle_bell",
      instrument: "Tinkle Bell",
      number: 112,
      category: "Percussive",
    },
    "113": {
      id: "agogo",
      instrument: "Agogo",
      number: 113,
      category: "Percussive",
    },
    "114": {
      id: "steel_drums",
      instrument: "Steel Drums",
      number: 114,
      category: "Percussive",
    },
    "115": {
      id: "woodblock",
      instrument: "Woodblock",
      number: 115,
      category: "Percussive",
    },
    "116": {
      id: "taiko_drum",
      instrument: "Taiko Drum",
      number: 116,
      category: "Percussive",
    },
    "117": {
      id: "melodic_tom",
      instrument: "Melodic Tom",
      number: 117,
      category: "Percussive",
    },
    "118": {
      id: "synth_drum",
      instrument: "Synth Drum",
      number: 118,
      category: "Percussive",
    },
    "119": {
      id: "reverse_cymbal",
      instrument: "Reverse Cymbal",
      number: 119,
      category: "Sound effects",
    },
    "120": {
      id: "guitar_fret_noise",
      instrument: "Guitar Fret Noise",
      number: 120,
      category: "Sound effects",
    },
    "121": {
      id: "breath_noise",
      instrument: "Breath Noise",
      number: 121,
      category: "Sound effects",
    },
    "122": {
      id: "seashore",
      instrument: "Seashore",
      number: 122,
      category: "Sound effects",
    },
    "123": {
      id: "bird_tweet",
      instrument: "Bird Tweet",
      number: 123,
      category: "Sound effects",
    },
    "124": {
      id: "telephone_ring",
      instrument: "Telephone Ring",
      number: 124,
      category: "Sound effects",
    },
    "125": {
      id: "helicopter",
      instrument: "Helicopter",
      number: 125,
      category: "Sound effects",
    },
    "126": {
      id: "applause",
      instrument: "Applause",
      number: 126,
      category: "Sound effects",
    },
    "127": {
      id: "gunshot",
      instrument: "Gunshot",
      number: 127,
      category: "Sound effects",
    },
  },
  byCategory: {
    piano: {
      acoustic_grand_piano: {
        id: "acoustic_grand_piano",
        instrument: "Acoustic Grand Piano",
        number: 0,
        category: "Piano",
      },
      bright_acoustic_piano: {
        id: "bright_acoustic_piano",
        instrument: "Bright Acoustic Piano",
        number: 1,
        category: "Piano",
      },
      electric_grand_piano: {
        id: "electric_grand_piano",
        instrument: "Electric Grand Piano",
        number: 2,
        category: "Piano",
      },
      honkytonk_piano: {
        id: "honkytonk_piano",
        instrument: "Honky-tonk Piano",
        number: 3,
        category: "Piano",
      },
      electric_piano_1: {
        id: "electric_piano_1",
        instrument: "Electric Piano 1",
        number: 4,
        category: "Piano",
      },
      electric_piano_2: {
        id: "electric_piano_2",
        instrument: "Electric Piano 2",
        number: 5,
        category: "Piano",
      },
      harpsichord: {
        id: "harpsichord",
        instrument: "Harpsichord",
        number: 6,
        category: "Piano",
      },
      clavinet: {
        id: "clavinet",
        instrument: "Clavinet",
        number: 7,
        category: "Piano",
      },
    },
    chromatic_percussion: {
      celesta: {
        id: "celesta",
        instrument: "Celesta",
        number: 8,
        category: "Chromatic Percussion",
      },
      glockenspiel: {
        id: "glockenspiel",
        instrument: "Glockenspiel",
        number: 9,
        category: "Chromatic Percussion",
      },
      music_box: {
        id: "music_box",
        instrument: "Music Box",
        number: 10,
        category: "Chromatic Percussion",
      },
      vibraphone: {
        id: "vibraphone",
        instrument: "Vibraphone",
        number: 11,
        category: "Chromatic Percussion",
      },
      marimba: {
        id: "marimba",
        instrument: "Marimba",
        number: 12,
        category: "Chromatic Percussion",
      },
      xylophone: {
        id: "xylophone",
        instrument: "Xylophone",
        number: 13,
        category: "Chromatic Percussion",
      },
      tubular_bells: {
        id: "tubular_bells",
        instrument: "Tubular Bells",
        number: 14,
        category: "Chromatic Percussion",
      },
      dulcimer: {
        id: "dulcimer",
        instrument: "Dulcimer",
        number: 15,
        category: "Chromatic Percussion",
      },
    },
    organ: {
      drawbar_organ: {
        id: "drawbar_organ",
        instrument: "Drawbar Organ",
        number: 16,
        category: "Organ",
      },
      percussive_organ: {
        id: "percussive_organ",
        instrument: "Percussive Organ",
        number: 17,
        category: "Organ",
      },
      rock_organ: {
        id: "rock_organ",
        instrument: "Rock Organ",
        number: 18,
        category: "Organ",
      },
      church_organ: {
        id: "church_organ",
        instrument: "Church Organ",
        number: 19,
        category: "Organ",
      },
      reed_organ: {
        id: "reed_organ",
        instrument: "Reed Organ",
        number: 20,
        category: "Organ",
      },
      accordion: {
        id: "accordion",
        instrument: "Accordion",
        number: 21,
        category: "Organ",
      },
      harmonica: {
        id: "harmonica",
        instrument: "Harmonica",
        number: 22,
        category: "Organ",
      },
      tango_accordion: {
        id: "tango_accordion",
        instrument: "Tango Accordion",
        number: 23,
        category: "Organ",
      },
    },
    guitar: {
      acoustic_guitar_nylon: {
        id: "acoustic_guitar_nylon",
        instrument: "Acoustic Guitar (nylon)",
        number: 24,
        category: "Guitar",
      },
      acoustic_guitar_steel: {
        id: "acoustic_guitar_steel",
        instrument: "Acoustic Guitar (steel)",
        number: 25,
        category: "Guitar",
      },
      electric_guitar_jazz: {
        id: "electric_guitar_jazz",
        instrument: "Electric Guitar (jazz)",
        number: 26,
        category: "Guitar",
      },
      electric_guitar_clean: {
        id: "electric_guitar_clean",
        instrument: "Electric Guitar (clean)",
        number: 27,
        category: "Guitar",
      },
      electric_guitar_muted: {
        id: "electric_guitar_muted",
        instrument: "Electric Guitar (muted)",
        number: 28,
        category: "Guitar",
      },
      overdriven_guitar: {
        id: "overdriven_guitar",
        instrument: "Overdriven Guitar",
        number: 29,
        category: "Guitar",
      },
      distortion_guitar: {
        id: "distortion_guitar",
        instrument: "Distortion Guitar",
        number: 30,
        category: "Guitar",
      },
      guitar_harmonics: {
        id: "guitar_harmonics",
        instrument: "Guitar Harmonics",
        number: 31,
        category: "Guitar",
      },
    },
    bass: {
      acoustic_bass: {
        id: "acoustic_bass",
        instrument: "Acoustic Bass",
        number: 32,
        category: "Bass",
      },
      electric_bass_finger: {
        id: "electric_bass_finger",
        instrument: "Electric Bass (finger)",
        number: 33,
        category: "Bass",
      },
      electric_bass_pick: {
        id: "electric_bass_pick",
        instrument: "Electric Bass (pick)",
        number: 34,
        category: "Bass",
      },
      fretless_bass: {
        id: "fretless_bass",
        instrument: "Fretless Bass",
        number: 35,
        category: "Bass",
      },
      slap_bass_1: {
        id: "slap_bass_1",
        instrument: "Slap Bass 1",
        number: 36,
        category: "Bass",
      },
      slap_bass_2: {
        id: "slap_bass_2",
        instrument: "Slap Bass 2",
        number: 37,
        category: "Bass",
      },
      synth_bass_1: {
        id: "synth_bass_1",
        instrument: "Synth Bass 1",
        number: 38,
        category: "Bass",
      },
      synth_bass_2: {
        id: "synth_bass_2",
        instrument: "Synth Bass 2",
        number: 39,
        category: "Bass",
      },
    },
    strings: {
      violin: {
        id: "violin",
        instrument: "Violin",
        number: 40,
        category: "Strings",
      },
      viola: {
        id: "viola",
        instrument: "Viola",
        number: 41,
        category: "Strings",
      },
      cello: {
        id: "cello",
        instrument: "Cello",
        number: 42,
        category: "Strings",
      },
      contrabass: {
        id: "contrabass",
        instrument: "Contrabass",
        number: 43,
        category: "Strings",
      },
      tremolo_strings: {
        id: "tremolo_strings",
        instrument: "Tremolo Strings",
        number: 44,
        category: "Strings",
      },
      pizzicato_strings: {
        id: "pizzicato_strings",
        instrument: "Pizzicato Strings",
        number: 45,
        category: "Strings",
      },
      orchestral_harp: {
        id: "orchestral_harp",
        instrument: "Orchestral Harp",
        number: 46,
        category: "Strings",
      },
      timpani: {
        id: "timpani",
        instrument: "Timpani",
        number: 47,
        category: "Strings",
      },
    },
    ensemble: {
      string_ensemble_1: {
        id: "string_ensemble_1",
        instrument: "String Ensemble 1",
        number: 48,
        category: "Ensemble",
      },
      string_ensemble_2: {
        id: "string_ensemble_2",
        instrument: "String Ensemble 2",
        number: 49,
        category: "Ensemble",
      },
      synth_strings_1: {
        id: "synth_strings_1",
        instrument: "Synth Strings 1",
        number: 50,
        category: "Ensemble",
      },
      synth_strings_2: {
        id: "synth_strings_2",
        instrument: "Synth Strings 2",
        number: 51,
        category: "Ensemble",
      },
      choir_aahs: {
        id: "choir_aahs",
        instrument: "Choir Aahs",
        number: 52,
        category: "Ensemble",
      },
      voice_oohs: {
        id: "voice_oohs",
        instrument: "Voice Oohs",
        number: 53,
        category: "Ensemble",
      },
      synth_choir: {
        id: "synth_choir",
        instrument: "Synth Choir",
        number: 54,
        category: "Ensemble",
      },
      orchestra_hit: {
        id: "orchestra_hit",
        instrument: "Orchestra Hit",
        number: 55,
        category: "Ensemble",
      },
    },
    brass: {
      trumpet: {
        id: "trumpet",
        instrument: "Trumpet",
        number: 56,
        category: "Brass",
      },
      trombone: {
        id: "trombone",
        instrument: "Trombone",
        number: 57,
        category: "Brass",
      },
      tuba: {
        id: "tuba",
        instrument: "Tuba",
        number: 58,
        category: "Brass",
      },
      muted_trumpet: {
        id: "muted_trumpet",
        instrument: "Muted Trumpet",
        number: 59,
        category: "Brass",
      },
      french_horn: {
        id: "french_horn",
        instrument: "French Horn",
        number: 60,
        category: "Brass",
      },
      brass_section: {
        id: "brass_section",
        instrument: "Brass Section",
        number: 61,
        category: "Brass",
      },
      synth_brass_1: {
        id: "synth_brass_1",
        instrument: "Synth Brass 1",
        number: 62,
        category: "Brass",
      },
      synth_brass_2: {
        id: "synth_brass_2",
        instrument: "Synth Brass 2",
        number: 63,
        category: "Brass",
      },
    },
    reed: {
      soprano_sax: {
        id: "soprano_sax",
        instrument: "Soprano Sax",
        number: 64,
        category: "Reed",
      },
      alto_sax: {
        id: "alto_sax",
        instrument: "Alto Sax",
        number: 65,
        category: "Reed",
      },
      tenor_sax: {
        id: "tenor_sax",
        instrument: "Tenor Sax",
        number: 66,
        category: "Reed",
      },
      baritone_sax: {
        id: "baritone_sax",
        instrument: "Baritone Sax",
        number: 67,
        category: "Reed",
      },
      oboe: {
        id: "oboe",
        instrument: "Oboe",
        number: 68,
        category: "Reed",
      },
      english_horn: {
        id: "english_horn",
        instrument: "English Horn",
        number: 69,
        category: "Reed",
      },
      bassoon: {
        id: "bassoon",
        instrument: "Bassoon",
        number: 70,
        category: "Reed",
      },
      clarinet: {
        id: "clarinet",
        instrument: "Clarinet",
        number: 71,
        category: "Reed",
      },
    },
    pipe: {
      piccolo: {
        id: "piccolo",
        instrument: "Piccolo",
        number: 72,
        category: "Pipe",
      },
      flute: {
        id: "flute",
        instrument: "Flute",
        number: 73,
        category: "Pipe",
      },
      recorder: {
        id: "recorder",
        instrument: "Recorder",
        number: 74,
        category: "Pipe",
      },
      pan_flute: {
        id: "pan_flute",
        instrument: "Pan Flute",
        number: 75,
        category: "Pipe",
      },
      blown_bottle: {
        id: "blown_bottle",
        instrument: "Blown Bottle",
        number: 76,
        category: "Pipe",
      },
      shakuhachi: {
        id: "shakuhachi",
        instrument: "Shakuhachi",
        number: 77,
        category: "Pipe",
      },
      whistle: {
        id: "whistle",
        instrument: "Whistle",
        number: 78,
        category: "Pipe",
      },
      ocarina: {
        id: "ocarina",
        instrument: "Ocarina",
        number: 79,
        category: "Pipe",
      },
    },
    synth_lead: {
      lead_1_square: {
        id: "lead_1_square",
        instrument: "Lead 1 (square)",
        number: 80,
        category: "Synth Lead",
      },
      lead_2_sawtooth: {
        id: "lead_2_sawtooth",
        instrument: "Lead 2 (sawtooth)",
        number: 81,
        category: "Synth Lead",
      },
      lead_3_calliope: {
        id: "lead_3_calliope",
        instrument: "Lead 3 (calliope)",
        number: 82,
        category: "Synth Lead",
      },
      lead_4_chiff: {
        id: "lead_4_chiff",
        instrument: "Lead 4 (chiff)",
        number: 83,
        category: "Synth Lead",
      },
      lead_5_charang: {
        id: "lead_5_charang",
        instrument: "Lead 5 (charang)",
        number: 84,
        category: "Synth Lead",
      },
      lead_6_voice: {
        id: "lead_6_voice",
        instrument: "Lead 6 (voice)",
        number: 85,
        category: "Synth Lead",
      },
      lead_7_fifths: {
        id: "lead_7_fifths",
        instrument: "Lead 7 (fifths)",
        number: 86,
        category: "Synth Lead",
      },
      lead_8_bass__lead: {
        id: "lead_8_bass__lead",
        instrument: "Lead 8 (bass + lead)",
        number: 87,
        category: "Synth Lead",
      },
    },
    synth_pad: {
      pad_1_new_age: {
        id: "pad_1_new_age",
        instrument: "Pad 1 (new age)",
        number: 88,
        category: "Synth Pad",
      },
      pad_2_warm: {
        id: "pad_2_warm",
        instrument: "Pad 2 (warm)",
        number: 89,
        category: "Synth Pad",
      },
      pad_3_polysynth: {
        id: "pad_3_polysynth",
        instrument: "Pad 3 (polysynth)",
        number: 90,
        category: "Synth Pad",
      },
      pad_4_choir: {
        id: "pad_4_choir",
        instrument: "Pad 4 (choir)",
        number: 91,
        category: "Synth Pad",
      },
      pad_5_bowed: {
        id: "pad_5_bowed",
        instrument: "Pad 5 (bowed)",
        number: 92,
        category: "Synth Pad",
      },
      pad_6_metallic: {
        id: "pad_6_metallic",
        instrument: "Pad 6 (metallic)",
        number: 93,
        category: "Synth Pad",
      },
      pad_7_halo: {
        id: "pad_7_halo",
        instrument: "Pad 7 (halo)",
        number: 94,
        category: "Synth Pad",
      },
      pad_8_sweep: {
        id: "pad_8_sweep",
        instrument: "Pad 8 (sweep)",
        number: 95,
        category: "Synth Pad",
      },
    },
    synth_effects: {
      fx_1_rain: {
        id: "fx_1_rain",
        instrument: "FX 1 (rain)",
        number: 96,
        category: "Synth Effects",
      },
      fx_2_soundtrack: {
        id: "fx_2_soundtrack",
        instrument: "FX 2 (soundtrack)",
        number: 97,
        category: "Synth Effects",
      },
      fx_3_crystal: {
        id: "fx_3_crystal",
        instrument: "FX 3 (crystal)",
        number: 98,
        category: "Synth Effects",
      },
      fx_4_atmosphere: {
        id: "fx_4_atmosphere",
        instrument: "FX 4 (atmosphere)",
        number: 99,
        category: "Synth Effects",
      },
      fx_5_brightness: {
        id: "fx_5_brightness",
        instrument: "FX 5 (brightness)",
        number: 100,
        category: "Synth Effects",
      },
      fx_6_goblins: {
        id: "fx_6_goblins",
        instrument: "FX 6 (goblins)",
        number: 101,
        category: "Synth Effects",
      },
      fx_7_echoes: {
        id: "fx_7_echoes",
        instrument: "FX 7 (echoes)",
        number: 102,
        category: "Synth Effects",
      },
      fx_8_scifi: {
        id: "fx_8_scifi",
        instrument: "FX 8 (sci-fi)",
        number: 103,
        category: "Synth Effects",
      },
    },
    ethnic: {
      sitar: {
        id: "sitar",
        instrument: "Sitar",
        number: 104,
        category: "Ethnic",
      },
      banjo: {
        id: "banjo",
        instrument: "Banjo",
        number: 105,
        category: "Ethnic",
      },
      shamisen: {
        id: "shamisen",
        instrument: "Shamisen",
        number: 106,
        category: "Ethnic",
      },
      koto: {
        id: "koto",
        instrument: "Koto",
        number: 107,
        category: "Ethnic",
      },
      kalimba: {
        id: "kalimba",
        instrument: "Kalimba",
        number: 108,
        category: "Ethnic",
      },
      bagpipe: {
        id: "bagpipe",
        instrument: "Bagpipe",
        number: 109,
        category: "Ethnic",
      },
      fiddle: {
        id: "fiddle",
        instrument: "Fiddle",
        number: 110,
        category: "Ethnic",
      },
      shanai: {
        id: "shanai",
        instrument: "Shanai",
        number: 111,
        category: "Ethnic",
      },
    },
    percussive: {
      tinkle_bell: {
        id: "tinkle_bell",
        instrument: "Tinkle Bell",
        number: 112,
        category: "Percussive",
      },
      agogo: {
        id: "agogo",
        instrument: "Agogo",
        number: 113,
        category: "Percussive",
      },
      steel_drums: {
        id: "steel_drums",
        instrument: "Steel Drums",
        number: 114,
        category: "Percussive",
      },
      woodblock: {
        id: "woodblock",
        instrument: "Woodblock",
        number: 115,
        category: "Percussive",
      },
      taiko_drum: {
        id: "taiko_drum",
        instrument: "Taiko Drum",
        number: 116,
        category: "Percussive",
      },
      melodic_tom: {
        id: "melodic_tom",
        instrument: "Melodic Tom",
        number: 117,
        category: "Percussive",
      },
      synth_drum: {
        id: "synth_drum",
        instrument: "Synth Drum",
        number: 118,
        category: "Percussive",
      },
    },
    sound_effects: {
      reverse_cymbal: {
        id: "reverse_cymbal",
        instrument: "Reverse Cymbal",
        number: 119,
        category: "Sound effects",
      },
      guitar_fret_noise: {
        id: "guitar_fret_noise",
        instrument: "Guitar Fret Noise",
        number: 120,
        category: "Sound effects",
      },
      breath_noise: {
        id: "breath_noise",
        instrument: "Breath Noise",
        number: 121,
        category: "Sound effects",
      },
      seashore: {
        id: "seashore",
        instrument: "Seashore",
        number: 122,
        category: "Sound effects",
      },
      bird_tweet: {
        id: "bird_tweet",
        instrument: "Bird Tweet",
        number: 123,
        category: "Sound effects",
      },
      telephone_ring: {
        id: "telephone_ring",
        instrument: "Telephone Ring",
        number: 124,
        category: "Sound effects",
      },
      helicopter: {
        id: "helicopter",
        instrument: "Helicopter",
        number: 125,
        category: "Sound effects",
      },
      applause: {
        id: "applause",
        instrument: "Applause",
        number: 126,
        category: "Sound effects",
      },
      gunshot: {
        id: "gunshot",
        instrument: "Gunshot",
        number: 127,
        category: "Sound effects",
      },
    },
  },
});

// TODO: Should this be packaged as a json.parse(string) at compile??
// console.log(JSON.stringify(GMInstruments));
